### ISSUE TITLE
Lockpick / Laundromat Bug????

### ISSUE THREAD

**Issue by FaFuze** [MaximilianAdF/NoPixel-MiniGames-4.0#14]
IDK if this is intended, but if only one of the circles match and no other circle is connected to other lines, that specific line is marked as completed although lines aren't connected to dots.

![scuff](https://github.com/MaximilianAdF/NoPixel-MiniGames-4.0/assets/103941281/47607484-b550-4067-9ae4-ba296621cd84)

**Comment by MaximilianAdF** [comment]
If you mean that there are more dots than there are those semi-circles, yes that is intended. From what I've seen NoPixel has the same logic. This makes it so there can be multiple solutions in those cases. 

Let me know if this clears it up.

**Comment by FaFuze** [comment]
ah yeah i wasnt sure if it was a bug or intended which is the reason for so many question marks lmao, thanks for clarifying
