### ISSUE TITLE
Change timer at bottom of minigames from 'linear' to 'cubic-bezier' to better match the timer used in NP.

### ISSUE THREAD

**Issue by FaFuze** [MaximilianAdF/NoPixel-MiniGames-4.0#16]
I believe NP uses a cubic-bezier timer and not a linear timer, as the timer slows down as it gets closer to the end.

[Heres a video that demonstrates it quite clearly](https://youtube.com/watch?v=3-5rTyt9YrQ&t=452)

**Comment by MaximilianAdF** [comment]
Thanks for the pointer, this will be updated with the new major UI / Interface update across the LockPick, Laundromat & RoofRunning minigames.

**Comment by MaximilianAdF** [comment]
Has been added to roofRunning now
