### ISSUE TITLE
[BUG] menu Link points to the wrong site address

### ISSUE THREAD

**Issue by danielsauceda** [MaximilianAdF/NoPixel-MiniGames-4.0#18]
On the site for the github pages
https://maximilianadf.github.io/NoPixel-MiniGames-4.0/index.html

the puzzle located here
https://maximilianadf.github.io/NoPixel-MiniGames-4.0/Laundromat/Laundromat.html

is not accessible from the menu

![image](https://github.com/MaximilianAdF/NoPixel-MiniGames-4.0/assets/11530180/d87ba41d-65a5-4c84-ae18-b535f9bea245)

Because the "L" in the link is lower case and not uppercase.
https://maximilianadf.github.io/NoPixel-MiniGames-4.0/Laundromat/laundromat.html

**Comment by MaximilianAdF** [comment]
Typo fixed, thanks.
