### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lazerrwolf** [MaximilianAdF/NoPixel-MiniGames-4.0#23]
Could you please provide me installation instructions for each of these minigames? Thanks! Thats all i need. Also do you have discord to discuss?

**Comment by MaximilianAdF** [comment]
You can play all the minigames on: https://maximilianadf.github.io/NoPixel-MiniGames-4.0/

If you want to download the games locally:
- Go to [the repoistory](https://github.com/MaximilianAdF/NoPixel-MiniGames-4.0) 
- In the top right, press the green "code" button
- Click "download zip"
- When the file has been downloaded, extract the files from the .zip
- If you want to run a game, go into the specific game folder and open the .html document in your preferred browser
