### ISSUE TITLE
can you please create a pincracker app nopixel 4.0

### ISSUE THREAD

**Issue by nox664** [MaximilianAdF/NoPixel-MiniGames-4.0#51]
https://www.twitch.tv/binks/clip/DeterminedEntertainingLettuceRickroll-dTLT6D7F_PXJlcg1?filter=clips&range=7d&sort=time
you minigames really help alot Thank you so much man for creating it

**Comment by MaximilianAdF** [comment]
Thank you for the kind words, I will get this new game done by tommorow

**Comment by MaximilianAdF** [comment]
Commit fdd1c4b19f83ad29c9822652aaddd8a45c6fcaca adds PinCracker as a new minigame

**Comment by nox664** [comment]
Can you please update the game
you can use back space now to delete numbers  
https://youtube.com/clip/UgkxtlPsgWwSrXMMAdkZpEeP4XwomXm0-ZE9?si=UAKaI6UQUVgO-ENh

**Comment by MaximilianAdF** [comment]
It should already have Backspace, do you mean Backspace or Delete button?

**Comment by nox664** [comment]
I need a delete button (backspace) because right now, the system is automatically deleting all numbers whenever I try to input the next one. I want more control over which numbers are deleted.
& Additionally, can you add an option to adjust the speed in the repair kit mini game to replicate the process of breaking handcuffs?
& thank you so much for fast response.

**Comment by MaximilianAdF** [comment]
Oh you mean after submitting, for the numbers to not be removed automatically? I can change it to that.

**Comment by nox664** [comment]
> Oh you mean after submitting, for the numbers to not be removed automatically? I can change it to that.


Yes, instead of deleting all numbers automatically after submitting, let me delete them with backspace.

**Comment by MaximilianAdF** [comment]
fixed in #57
